/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.*;
import javax.swing.text.html.parser.Parser;
import java.awt.event.PaintEvent;
import java.util.Arrays;

/**
 *
 * @author Joham Morales
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entrada_Productos = new javax.swing.JTextField();
        Boton_iniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Entrada_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_ProductosActionPerformed(evt);
            }
        });

        Boton_iniciar.setText("Inciar");
        Boton_iniciar.setName("Boton_Iniciar"); // NOI18N
        Boton_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciarActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir consola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(Entrada_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(Boton_iniciar))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_iniciar))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciarActionPerformed
        // TODO add your handling code here:
        try {
            Primera_LINEA.P_Estado_primera_L = 1;
            Primera_LINEA.P_Estado_segunda_l = 1;
            Primera_LINEA.P_Estado_tercera_l = 1;

            JOptionPane.showMessageDialog(null,"Iniciando con: "+(Entrada_Productos.getText())+" productos");
            // ponemos el valor a la variable global productos
            Proyecto.Productos = Integer.parseInt(Entrada_Productos.getText());
            // variable para las matrices
            int productos = Integer.parseInt(Entrada_Productos.getText());
            String[][] elementos = new String[productos+1][21];
            String[][] tiempo = new String[productos+1][5];
            // Maquetación de las matrices
            // Matriz Elementos
            elementos[0][0] = "Producto";elementos[0][1] = "Primera Linea";elementos[0][2] = "1";elementos[0][3] = "2";
            elementos[0][4] = "3";elementos[0][5] = "Segunda Linea";elementos[0][6] = "1";elementos[0][7] = "2";
            elementos[0][8] = "3";elementos[0][9] = "4";elementos[0][10] = "5";elementos[0][11] = "6";
            elementos[0][12] = "Tercera Linea";elementos[0][13] = "1";elementos[0][14] = "2";elementos[0][15] = "3";
            elementos[0][16] = "4";elementos[0][17] = "5";elementos[0][18] = "6";elementos[0][19] = "7";
            elementos[0][20] = "8";
            // Matriz Tiempo
            tiempo[0][0] = "Producto";tiempo[0][1] = "Primera Linea";tiempo[0][2] = "Segunda Linea";tiempo[0][3] = "Tercera linea";
            tiempo[0][4] = "Total";
            // guardamos las matrices en nuestras variables locales
            Proyecto.Matriz_Elementos = elementos;
            Proyecto.Matriz_Tiempos = tiempo;
            Proyecto.Iniciar();
        }
        catch (Exception error){
            JOptionPane.showMessageDialog(null, "se presento un error al iniciar el programa " +
                    "\ningrese un numero por favor\n"+error);
        }
    }//GEN-LAST:event_Boton_iniciarActionPerformed

    private void Entrada_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_ProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null,"Imprimiendo en consola");
            System.out.println(Proyecto.A+"\n___________________________________________________________"+Proyecto.r);
            for (int i=0; i<Proyecto.Matriz_Elementos.length ; i++){
                for (int j=0; j<21;j++){
                    System.out.print(Proyecto.AZ+" | "+Proyecto.r+Proyecto.Matriz_Elementos[i][j]);
                }
                System.out.println();
            }
            System.out.println();
            System.out.println(Proyecto.A+"\n___________________________________________________________"+Proyecto.r);
            for (int i=0; i<Proyecto.Matriz_Tiempos.length ; i++){
                for (int j=0; j<5;j++){
                    System.out.print(Proyecto.AZ+" | "+Proyecto.r+Proyecto.Matriz_Tiempos[i][j]);
                }
                System.out.println();
            }
            System.out.println("\n TABLAS FINALIZADAS");

        }catch (Exception error){
            System.out.println("error "+error);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_iniciar;
    private javax.swing.JTextField Entrada_Productos;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
